version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./desafio
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./front-end/transaction-app
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: