FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build --prod

FROM nginx:alpine

COPY --from=0 /app/dist/transaction-app /usr/share/nginx/html

# Expose port 80
EXPOSE 8081

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]